{% set name = "vapory" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/V/Vapory/Vapory-{{ version }}.tar.gz
  sha256: e0213caaac5cbb1d336ef7455a18e7ffcc8b864093040958ef45bddac8204231

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - povray

test:
  imports:
    - vapory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Zulko/vapory
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Photo-realistic 3D rendering with Python and POV-Ray

  description: |
    Vapory is a Python library to render photo-realistic 
    3D scenes with the free ray-tracing engine POV-Ray.
  doc_url: https://github.com/Zulko/vapory
  dev_url: https://github.com/Zulko/vapory

extra:
  recipe-maintainers:
    - jan-janssen
